-
  name:  'Form Post Requests'
  uriPattern: '<FormPostRequestsSubRoutes>'
  defaults:
    '@package': 'Neos.Neos'
    '@controller': 'Frontend\Node'
    '@action': 'show'
    '@format': 'html'
  httpMethods: ['POST']
  routeParts:
    'node':
      handler: 'Neos\Neos\Routing\FrontendNodeRoutePartHandlerInterface'
  subRoutes:
    'FormPostRequestsSubRoutes':
      package: 'Neos.Neos'
      suffix: 'FormPostRequests'
      variables:
        'defaultUriSuffix': '<defaultUriSuffix>'