
ObisConcept:
  NeosPhp:
    templatePathAndFilename: 'resource://ObisConcept.NeosPhp/Private/Templates/PhpScript/index.html'
Neos:
  Flow:
    mvc:
      'ObisConcept.NeosPhp': true
  Neos:
    userInterface:
      translation:
        autoInclude:
          ObisConcept.NeosPhp:
            - Main
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        ObisConcept.NeosPhp: true
